---
title: Practicals
---

{{< include ../_links.qmd >}}

# General info

There are 8 practicals during the term.
Practicals will be done in teams of 1-3 for the entire term.
Please bring your laptop and make sure to have a recent version of [`R`][cran] (4.0.0 or higher) as well as a R IDE such as [`RStudio`][rstudio_d] or [`VSCode`][vscode_d].
Finally it is highly recommended to also have [`quarto`][quarto_install] software to produce reproducible reports.

You will find all the practicals exercises in the book ["On the R way to hell"][r_way_en] with specific chapters to read and work on indicated in the [schedule](lectures.qmd) (for an overview see [here][r-chap-en]).

As part of the course you will have to submit lab reports (see [Assessments](assessment.qmd) for details).

I strongly suggest to read the practical material before coming, then used the first half of the practical to go through the exercises and take the second half to start working on the lab reports.

To write lab reports you can use quarto to produce nicely and easily formatted document in a reproducible manner. A template of a quarto document will be provided for each lab report.
