---
title: Syllabus
---

{{< include ../_links.qmd >}}

# Course description

Applied biostatistics to real problems.
Experimental design and data collection.
Consequences of violating assumptions of different tests.
Monte Carlo and Bootstrap analysis.
Case studies and exercises in using statistical analysis packages.

The course covers the fundations of statistics (distributions, CIs, p-values, central limit theorem, Bayesian thinking, ...) and linear models (t-test, ANOVA, regression, ANCOVA, general linear model) using R.

# Classes

* Duration: 2 lectures of 1h20 and a 2h50 practical each week
* Style: mix of lecture, discussion and practical
* How: In-person. 
* Course info and slides: <https://biostats-uottawa.github.io/bioXx58/>
* Lab manual: <https://biostats-uottawa.github.io/Rway/>

{{< include who_when.qmd >}}

See the [course website](lectures.qmd) for details of the schedule

# Prerequisite

MAT 2379/2779 or an equivalent introductory statistics course

# Course objectives

* Understand the fundamental principles of statistical inference
* Understand the general principles underlying the most common tests
* Know the assumptions underlying common tests and understand the impact of violating them
* Be able to perform standard statistical analyses using R
* Acquire the capacity to correctly interpret the statistical and biological significance of statistical tests

# Organization

Lectures and class discussions on most common statistical tests.

Laboratory exercises that illustrate main concepts and allow application of theory to real situations.

# Texts and software

* (recommended but not mandatory) Motulsky, H. J. Intuitive biostatistics. 4th Edition. Oxford University Press, available at the uOttawa bookstore. Used copies of the 4th edition should be around (we used it last year); used copies of the 3rd edition would also be fine.
Errata: See here for corrections to errors in the 2nd, 3rd and 4th edition.
* R - a free software environment for statistical computing and graphics. It compiles and runs on a wide variety of UNIX platforms, Windows and MacOS. To download R, please follow this link and then choose your preferred CRAN mirror. 

# Evaluation
{{< include assessment.qmd >}}


# Marking disputes
If you feel an error has been made in the grading of an assignment or exam, you have 10 working days from the date the item was returned to request a regrading. Beyond 10 working days the mark is considered final. If the issue concerns a lab assignment, please consult the TA that marked it; if it concerns and exam, please see the course instructor.

When a regrading occurs, the new mark will stand whether it is higher or lower, so there is no guarantee your mark will increase. Simple adding mistakes unfortunately happen on occasion given the volume of assignments and exams we have to mark and such cases are easy to correct. However, disputes over partial marks on partially correct answers will not always work out in your favour and should be reserved for situations in which you feel you have a strong case. When requesting a regrading, you must provide an explanation as to what you feel the issue is (i.e. why you think you deserve a higher grade). The more specific this is the better your chance of success.

I do not consider arguments for additional marks simply because you are close to the next letter grade.




# Attendance
As per uOttawa policy, to ensure they succeed in all courses of their program of study, students have the responsibility to participate in the various learning and assessment activities for this course. Attendance of the lectures and laboratory are not formally required for this course, although both are STRONGLY recommended. The supplied lecture slides will not include all content presented and discussed in class, and teaching assistants and the professor are available during the labs for help with exercises and assignments. TA and professor office hours are to allow you an opportunity to ask questions related to course material and cannot replace a missed lecture or lab.

# University of Ottawa regulations 

## Academic integrity 

Academic integrity is fundamental to all scholarly activity. Every member of the University community has the moral obligation to learn and share knowledge with honesty and integrity. Students should be proud to show their diploma, knowing that they’ve earned it honestly and by respecting the principles of academic integrity. Academic fraud and plagiarism create irreparable inequities in our community by devaluing the work of others. Because academic integrity is so important, uOttawa created the following website to provide you with information and tools to identify and avoid academic fraud, and to understand its consequences, accessible [here](https://www2.uottawa.ca/current-students/academic-integrity). 

With respect to all BIO 4158/5158, unless otherwise specified as a group activity, you are expected to work individually, not to pass off the work of others as your own (i.e., no plagiarism), and not to post questions or answers online. Academic fraud is a very serious issue, and we treat it as such. Cases will be dealt with following uOttawa’s procedures outlined in [Academic regulation A-4](https://www.uottawa.ca/about-us/leadership-governance/policies-regulations/a-4-academic-integrity-academic-misconduct). 

## Plagiarism & the use of Artificial Intelligence
Plagiarism is the act of passing off someone else’s words or ideas as your own. Plagiarism is a serious academic offence and is also illegal. We uphold the law. This being said, scientific writing often uses other peoples’ ideas or words, so it is critical that you understand what constitutes plagiarism, and how you can avoid it. Proper referencing of other people’s ideas and results, and quotation with citation when directly borrowing phrases, are key. 
 
Artificial intelligence (AI), like ChatGPT, is a tool that can, like many, be used appropriately or unethically. In BIO 4158/5158, it is acceptable to use AI to improve the presentation of ideas, criticisms, or concepts that are yours. In this sense, AI is like Grammarly and other tools that have been around for some time. Using it as a tool to (hopefully) improve your communication is ethical. A word of caution, however: AI can alter the meaning of text you give it, even if instructed only to ‘polish’ the writing. Like other tools, it is up to you to ensure that you are using it effectively. Blind application, without careful review of the output, could easily create more problems than it solves. 

 
On the other hand, it is a form of plagiarism (i.e., unethical) to use AI to generate ideas, critiques, or concepts (i.e., the academic/scientific content). That is, AI should not be used to replace your understanding of the topic. And be forewarned, AI can be poor at this. It will produce something that, at first glance, seems well written, but a closer consideration of the scientific content reveals it to be problematic. More importantly, you are at university to learn; plagiarising hampers, not helps, this. 

 
## [Bilingualism](https://www.uottawa.ca/about-us/leadership-governance/policies-regulations/a-1-bilingualism) 

Please also note the University of Ottawa Regulation on [bilingualism](https://www.uottawa.ca/about-us/leadership-governance/policies-regulations/a-1-bilingualism): 

> “Except in programs and courses for which language is a requirement, all students have the right to produce their written work and to answer examination questions in the official language of their choice, regardless of the course’s language of instruction.” 

 

## Information about other Academic Regulations.

[See here](https://www2.uottawa.ca/about-us/policies-regulations/) 

# Student services 

## [Health and Wellness Services](https://www.uottawa.ca/campus-life/health-wellness/student-health-wellness-centre) 

There are many different services to help with everyday and crisis situations. Be proactive and visit the site to see what you can do to make your year more enjoyable. 

## [Academic Support University Wide](https://www.uottawa.ca/current-students/career-experiential-learning) 

- Academic Accommodations 
- Academic Reset 
- Academic Writing Help Center 

## [Career Corner](https://www.uottawa.ca/current-students/career-experiential-learning) 

Career Services offers various services and a career development program to enable you to recognize and enhance the employability skills you need in today's world of work. https://www.uottawa.ca/current-students/career-experiential-learning

 

# Equity, diversity and inclusion 

In this course, students of all races, colours, cultures, ethnicities, genders, and sexualities are welcome. We commit to providing a learning environment that fosters diversity, equity, and inclusion. A commitment to equity, diversity, and inclusion (EDI) is a process that requires ongoing action and reflection. We recognize the importance of this commitment to promoting a healthy educational community and to the success of all students. 

BIO4158/5158 is a space of respect for everyone, including students and professors. In support of this, as a code of conduct, we require that participation in this course is based on principles of inclusion, respect, and tolerance. We cannot, and will not, accept abusive or discriminatory behavior. 

 