project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
#    - "!slides/"
  resources:
#    - "slides/"
    - "data/"
#execute:
#  freeze: auto
website:
  google-analytics: G-6LLMGL3T2Q
  title: "Bio4x58-5x58"
#  margin-header: "![](/img/logo_hex.png){width='100px'}"
  description: "Intro. Biostat."
  favicon: /img/logo_hex.png
  site-url: https://biostats-uottawa.github.io/bioXx58/
  repo-url: https://github.com/biostats-uottawa/bioXx58/
  repo-actions: [issue]
  navbar:
    title: '![](/img/logo_hex.png){width="50px"} Intro Biostats & R (BioXx58)' 
    left:
      - text: Biostats uOttawa
        href: https://biostats-uottawa.github.io/
#      - text: Intro Biostats & R (BioXx58)
#        href: https://biostats-uottawa.github.io/bioXx58/
      - text: Biostats adv. / av.(Bio8940)
        href: https://biostats-uottawa.github.io/bio8940/
      - text: Livre / Book
        menu:
          - text: R-way to hell
            href: https://biostats-uottawa.github.io/R/en/
          - text: Chemin de l'enf-R
            href: https://biostats-uottawa.github.io/R/fr/
    # right:
    #   - icon: github
    #     menu:
    #     - text: Code
    #       href: https://github.com/biostats-uOttawa/bio8940
    #     - text: Issues
    #       href: https://github.com/Biostats-uOttawa/bio8940/issues
  sidebar:
    - id: fr
      title: "Français"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - icon: flag
          text: English (Bio4158/5158)
          href: en/index.qmd
        - text: Info générale
          href: fr/index.qmd
        - text: Calendrier
          href: fr/lectures.qmd
        - text: Labo
          href: fr/practical.qmd
        - text: Évaluation
          href: fr/assessment.qmd
        - fr/dataset.qmd
        - fr/syllabus.qmd
        - icon: envelope
          text: Contact
          href: fr/people.qmd
    - id: en
      title: "English"
      style: "floating"
      collapse-level: 2
      contents:
        - icon: flag
          text: Français (Bio4558/5558)
          href: fr/index.qmd
        - text: Course info
          href: en/index.qmd
        - text: Schedule
          href: en/lectures.qmd
        - text: Practicals
          href: en/practical.qmd
        - text: Assessments
          href: en/assessment.qmd
        - en/dataset.qmd
        - en/syllabus.qmd
        - icon: envelope
          text: "Contact"
          href: en/people.qmd
format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    highlight: kate
    fig_align: center
    css: css/biostat.css
    toc: true

bibliography: [biblio/bio8940_zot.bib, biblio/book.bib]
biblio-style: apalike
csl: biblio/ecology.csl
