{{< include ../_links.qmd >}}

## Pondérations d'évaluation

### Bio4558

- Travaux de laboratoire : 40% (8 rapports pendant le trimestre, 5% chacun)
- Examen de mi-parcours (pendant le laboratoire après la semaine de lecture) : 20%
- Examen final (pendant la semaine d'examen) : 40%

### Bio5558

- Travaux de laboratoire : 40% (8 rapports pendant le trimestre, 5% chacun)
- Examen de mi-parcours (pendant le laboratoire après la semaine de lecture) : 20%
- Rapport final (à soumettre avant la semaine d'examen) : 40%

## Travaux de laboratoire

Les rapports écrits comptent pour 40% de la note finale.
Il y a 8 rapports et ils comptent donc pour 5% chacun.
Vous pouvez travailler individuellement ou en équipe jusqu'à trois (cette dernière est encouragée).
Si vous soumettez un travail d'équipe, tous les membres de l'équipe recevront la même note, sauf circonstances exceptionnelles.
Vous devez soumettre une seule copie PDF de vos travaux avec les noms et identifiants de tous les étudiants en haut de la page (soumettre une seule copie pour le groupe).
Les travaux en retard seront pénalisés de 10 % par jour ou partie de jour.
Les devoirs consisteront soit en une série de questions auxquelles il faudra répondre, soit en une analyse statistique à effectuer.
 Un barème de notation spécifique est fourni pour chaque rapport sur [Brightspace][brightspace]

## Examens

### Mi-session

Durée de 1h30 après la semaine de relâche durant la période de labo.
En classe (voir l'horaire pour la date), livre ouvert, les calculatrices sont autorisées.
Aucun rattrapage ne sera proposé.

L'examen de mi-session sera disponible sur le site web du cours par la suite ; si vous ne le passez pas officiellement (par exemple, pour des raisons médicales), je vous suggère fortement de l'essayer sur votre temps libre. Nous nous ferons un plaisir de le noter pour vous donner un feedback (votre note ne sera pas prise en compte dans votre note finale). Ceux qui manquent l'examen de mi-parcours et ne le font pas ont généralement de mauvais résultats à l'examen final.

### Examen final (Bio4558 uniquement)

Il s'agit d'un examen à livre ouvert, les notes de cours et les calculatrices étant autorisées. L'examen durera 3h et posera des questions théoriques et pratiques, y compris quelques petits calculs. Il n'est pas nécessaire d'exécuter un code R.

## Rapport supplémentaire (Bio5558 uniquement)

L'évaluation finale prendra la forme d'un rapport écrit de l'analyse des données (unique pour chaque étudiant) de 15 pages à soumettre avant la période d'examen.
