{
  "hash": "c0abbfde4dfd4d4f8bf42eb4f8672469",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Introduction to linear mixed models?\"\nsubtitle: Harnessing random effects\nauthor: Julien Martin\ninstitute:  BIO 8940 - Lecture 6\ndate: today\nfrom: markdown+emoji\nformat:\n  revealjs: \n    width: 1600\n    height: 950\n    chalkboard: true\n    theme: [default]\n    css: [assets/theme_chalk/whiteboard-blue.css]\n#    output-location: column-fragment\n#    logo: assets/MAD_logo_small_rb.png\n    footer: BIO 8940 - Lecture 6\n    show-notes: false\n    output-ext: slides.html\n  html:\n    self-contained: true\n    number-sections: true\n    code-link: true\n    format-links: false\n    css: assets/css/notes.css\n    number-depth: 2\n    comments:\n      hypothesis: true\n    output-ext: notes.html\neditor:\n  render-on-save: false\n---\n\n\n\n\n# When you are lacking independence ...\n\n\n\n\n\n\n\n\n\n## Mixed models to the rescue!\n\n* Almost all biological data is inherently grouped\n\n  * Lakes\n\n  * Incubators\n\n  * Individual animals/plants \n\n  * Sites\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n### Mixed models should probably be the rule, not the exception\n\n::: {.notes}\nGive examples and discuss\n:::\n\n## Advantages of mixed models\n\n* Allows us to account for repeated measurements on the same group\n\n* Allows for missing data. Does not drop entire subject if missing one\nobservation for that subject.\n\n* Helps limit problem of over-fitting many different parameters\n\n* Avoids the need to average within a group which underestimates the true variation\n\n::: {.notes}\n* Impact of factor with 50 levels on df vs 1 random effect with 50 level\n* Underestimation true variation = overconfidence in results and lower p-values\n:::\n\n## Linear model so far\n\n\n$$\nY_i = \\underbrace{ a + \\sum_k^n b_k X_{k_i}}_\\text{fixed} + \\underbrace{\\epsilon_i}_\\text{random}\n$$\n\n$$\\epsilon_i \\sim N(0, {\\sigma_{\\epsilon}}^2)$$\n\n- Fixed part:\n    - describe deterministic processes.\n\n- Random part:\n    - describe stochastic processes.\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n### Problems when\n\n1. Observations are not independent (**Pseudo-replication**)\n1. Heterogeneous variance\n\n\n\n## Extending the linear model\n\n$$\nY_{ij} = \\underbrace{a + \\sum_k^n b_k X_{k_{ij}}}_\\text{fixed} + \\underbrace{\\epsilon_{ij} + a_j}_\\text{random}\n$$\n\n$$\\epsilon_{ij} \\sim N(0, {\\sigma_{\\epsilon}}^2)$$\n\n$$\na_j \\sim N(0, {\\sigma_{a}}^2)\n$$\n\n- Fixed part:\n    + Same as before.\n\n- Random part:\n    + Include grouping variables structuring the data\n\n# Example\n\n## The data\n\nMarine benthic data from nine inter-tidal areas along the Dutch coast collected by the Dutch institute RIKZ in the summer of 2002. In each inter-tidal area (denoted by ‘beach’), five samples were taken, and the macro-fauna and abiotic variables were measured.\n\n- **Sample**: sample number\n\n- **Richness**: species richness\n\n- **Exposure**: index composed of the surf zone, slope, grain size, and depth of anaerobic layer\n\n- **NAP**: height of sampling station compared to mean tidal level\n\n- **Beach**: beach identifier\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n  Sample Richness Exposure    NAP Beach\n1      1       11       10  0.045     1\n2      2       10       10 -1.036     1\n3      3       13       10 -1.336     1\n4      4       11       10  0.616     1\n5      5       10       10 -0.684     1\n6      6        8        8  1.190     2\n```\n\n\n:::\n:::\n\n\n\n\n## Data structure\n\n\n\n\n```{dot}\n//| echo: false\n//| eval: false\n//| file: assets/img_l6/data_structure.dot\ngraph G {\n  layout=neato\n//  viewport=\"1000,1000,2,'a'\"\n  a [label = \"Study\"]\n subgraph cluster_beach {\n  \tnode [style=filled, color=pink];\n    b1 [label = \"Beach 1\"];\n    b2 [label = \"Beach 2\"];\n    b3 [label = \"Beach 3\"];\n    label = \"Exposure\";\n  }\n  subgraph site {\n    label=\"NAP\";\n    color=blue;\n  \tnode [style=filled, color=lightblue];\n    graph [ordering=out]\n    s1 [label =\"Site 1\"]\n    s2 [label =\"Site 2\"]\n    s3 [label =\"Site 3\"]\n    s4 [label =\"Site 4\"]\n    s5 [label =\"Site 5\"]\n    s6 [label =\"Site 6\"]\n    s7 [label =\"Site 7\"]\n    s8 [label =\"Site 8\"]\n    s9 [label =\"Site 9\"]\n    s10 [label =\"Site 10\"]\n    s11 [label =\"Site 11\"]\n    s12 [label =\"Site 12\"]\n    s13 [label =\"Site 13\"]\n    s14 [label =\"Site 14\"]\n    s15 [label =\"Site 15\"]\n  }\n  a -- {b1 b2 b3};\n  b1 -- {s1  s2  s3  s4  s5};\n  b2 -- {s6  s7  s8  s9  s10};\n  b3 -- {s11  s12  s13  s14  s15};\n}\n```\n\n\n\n\n![](assets/img_l6/test.svg){fig-align=\"center\"}\n\n## Traditional linear model\n\n\\\n\n$$Richness_{i} = a + b_1\\ NAP_{i} + b_2\\ Exposure_{i} + \\epsilon_{i}$$\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n\\\n\n### What are the problems? \n\n::: {.notes}\n**Pseudo-replication**\n* Exposure varies only across beaches not within\n* Sites within a beach are not independent\n:::\n\n## 2 processes at 2 different levels\n\n1. Within a beach effect: **NAP**\n\n\\\n\n1. Between beaches effect: **Exposure**\n\n## Within a beach\n\n* Equation for each beach\n\n$$Richness_{i1} = a_1 + b_{1_1}\\ NAP_{i1} + \\epsilon_{i1}$$ \n$$Richness_{i2} = a_2 + b_{1_2}\\ NAP_{i2} + \\epsilon_{i2}$$ \n\n::: {style='text-align: center;'}\n...\n:::\n\n$$Richness_{i9} = a_9 + b_{1_9}\\ NAP_{i9} + \\epsilon_{i9}$$\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n9 equations and 27 parameters **Not great**\n\nOverall, \n$$Richness_{ij} = a_j + b_{1_j}\\ NAP_{ij} + \\epsilon_{ij}$$\n \n## Between beaches\n\n* Cannot simply do $Richness \\sim Exposure$\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n * In \n$$\nRichness_{ij} = a_j + b_{1_j}\\ NAP_{ij} + \\epsilon_{ij}\n$$ \n \nWhat captures the effect of `Exposure`\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n* Can we do ?\n\n$$\na_{j} = a + b_{exp}\\ exposure_{j} + \\epsilon_{j}\n$$ \n\n## Within and between beaches effects\n\n\\\n\n* within effects -> 27 parameters\n\n\\\n\n* Between effects -> 3 parameters\n\n\\\n\n::: {style='text-align: center;'}\n\n### Total 30 parameters\n### :scream: :sob:\n### (with 3 being stats-on stats) \n\n:::\n\n## Estimating both simultaneously\n\n$$\nRichness_{ij} = (a + a_j) + b_1 NAP_{ij} + b_2 Exposure_j + \\epsilon_{ij}\n$$\n\n- **a** is the general intercept\n- **a~j~** are the deviation from $a$ for each beach\n- **b~1~** and **b~2~** are the intercept and slope for the average beach\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n$$\nRichness_{ij} = \\underbrace{a + b_1{NAP_{ij}} + b_2{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n\n$$a_j \\sim N(0, {\\sigma_{a}}^2)$$\n$$\\epsilon_{ij} \\sim N(0, {\\sigma_{\\epsilon}}^2)$$\n\n### :smiley: 5 parameters estimated :smiley: {style=\"text-align: center;\"}\n\n\n:::{.notes}\n* assuming same NAP effect on each beach\n* assuming same residual variance for each beach\n:::\n\n## Fixed and random effects\n\n### Fixed\n\n* a, b~1~ and b~2~ estimated with a given error\n\n\\\n\n### Random\n\n* **a~j~** not estimated directly but assumed to come from a Gaussian distribution with a mena of 0 and an estimated Variance\n\n$$\na_j \\sim N(0, {\\sigma^2_{a_j}})\n$$\n\n## Fixed part\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-06_intro_lmm_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=3600}\n:::\n:::\n\n\n\n\n$$y_{ij} = \\underbrace{\\color{red}{a + b_1{NAP_{ij}}} + b_2{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}$$\n\n## Random part\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-06_intro_lmm_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=3600}\n:::\n:::\n\n\n\n\n$$\nRichness_{ij} = \\underbrace{\\color{red}{a + b_1{NAP_{ij}}} + b_2{Exposure_j}}_\\text{fixed} + \\color{purple}{\\underbrace{a_j + \\epsilon_{ij}}_\\text{random}}\n$$\n\n## R model output\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(mod.mix)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: Richness ~ NAP + scale(Exposure, scale = F) + (1 | Beach)\n\nREML criterion at convergence: 225.5\n\nScaled residuals: \n    Min      1Q  Median      3Q     Max \n-1.3462 -0.5025 -0.2306  0.2150  4.2746 \n\nRandom effects:\n Groups   Name        Variance Std.Dev.\n Beach    (Intercept) 0.3378   0.5812  \n Residual             9.3735   3.0616  \nNumber of obs: 45, groups:  Beach, 9\n\nFixed effects:\n                           Estimate Std. Error t value\n(Intercept)                  6.6256     0.5221  12.691\nNAP                         -2.6941     0.4700  -5.732\nscale(Exposure, scale = F)  -3.0005     0.5417  -5.539\n\nCorrelation of Fixed Effects:\n            (Intr) NAP   \nNAP         -0.313       \nscl(Ex,s=F)  0.015 -0.047\n```\n\n\n:::\n:::\n\n\n\n\n## Estimated equation\n\n$$\nRichness_{ij} = \\underbrace{6.63 -2.69{NAP_{ij}} -3{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n$$\na_j \\sim N(0, 0.34)\n$$\n\n$$\n\\epsilon_{ij} \\sim N(0, 9.37)\n$$\n\n## BLUPs ($a_j$) are shrunk\n\n- Estimates for each groups are constrained (shrunk) too avoid extreme values.\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-06_intro_lmm_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=3600}\n:::\n:::\n\n\n\n\n# Variance components\n\n## Modelling the variance\n\n- We estimated the variance explained by the model\n\n${\\sigma_{\\hat{y}}}^2$.\n\n- We decomposed teh residual variance in 2 :\n    + ${\\sigma_a}^2$ : across beach variance\n    + ${\\sigma_{\\epsilon}}^2$ Variation not associated to beaches (*i.e.* within-beach variance)\n\n## Estimating repeatability\n\n- **Repeatability** Proportion of (residual) variance associated to among levels of a random effect.\n\n- Here variation associated to among beach differences\n\n$$\nRichness_{ij} = \\underbrace{a + b_1{NAP_{ij}} + b_2{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n$$\na_j \\sim N(0, {\\sigma_a}^2)\n$$\n\n$$\\epsilon \\sim N(0, {\\sigma_{\\epsilon}}^2)$$\n\n$$ r = \\frac{{\\sigma_a}^2}{{\\sigma_a}^2 + {\\sigma_{\\epsilon}}^2}$$\n\n\n## With our model\n\n\n\n\n\n\n\n\n\n$$\nRichness_{ij} = \\underbrace{37.3 -2.69{NAP_{ij}} -3{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n$$a_j \\sim N(0, 0.34)$$\n\n$$\\epsilon_{ij} \\sim N(0, 9.37)$$\n\n\\\n\n$$\nr^2 = \\frac{0.34}{0.34 + 9.37}\n= \\frac{0.34}{9.71}\n= 0.03\n$$\n\n## Repeatability is conditioned on fixed effects\n\nDifferences among groups can be explained by fixed effects and thus influence ${\\sigma_a}^2$ \n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\nWe can estimate repeatability with 2 models for example:\n\n* With exposure\n$$\nRichness_{ij} = \\underbrace{a + b_1{NAP_{ij}} + b_2{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n* or without\n\n$$\nRichness_{ij} = \\underbrace{a + b_1{NAP_{ij}}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n## Repeatability With exposure effects\n\n$$\nRichness_{ij} = \\underbrace{37.3 -2.69{NAP_{ij}} -3{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n$$\na_j \\sim N(0, 0.338)\n$$\n\n$$\n\\epsilon_{ij} \\sim N(0, 9.374)\n$$\n\n$$\nr\\ (with\\ exposure) = \\frac{0.338}{0.338 + 9.37} = 0.03\n$$\n\n## Repeatability without exposure\n\n$$\nRichness_{ij} = \\underbrace{6.58 -2.57{NAP_{ij}}}_\\text{fixed} + \\underbrace{a_j + \\epsilon_{ij}}_\\text{random}\n$$\n\n$$\na_j \\sim N(0, 8.668)\n$$\n\n$$\n\\epsilon_{ij} \\sim N(0, 9.362)\n$$\n\n$$\nr\\ (without\\ exposure) = \\frac{8.668}{8.668 + 9.36} = 0.48\n$$\n\n# Models with multiple random effects\n\n## When tricky becomes trickier\n\n- Complex model use only when necessary\n\n- Easy to build a nonsensical models which is over-parametrized ...\n\n### Key to understand differences between random effect types\n\n## Nested effects\n\nB is nested within A if each level of B is present in only 1 level of B\n\n![](assets/img_l6/nested.png){fig-align=\"center\"}\n\n## Crossed effects\n\nA and B are crossed .. when they are not nested :stuck_out_tongue_winking_eye:\n\nA and B are fully crossed when all levels of B are present in all levels of A\n\n![](assets/img_l6/crossed.svg){fig-align=\"center\" width=\"100%\"}\n\n## Random regression\n\n- Previous model assumed that NAP effect was the same for all beaches\n\n::: {style=\"text-align: center;\"}\n**This might not be true**\n:::\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n- Beaches might vary in both their `mean Richness` and their `response to NAP`\n\n$$\nRichness_{ij} = \\underbrace{a + b_1{NAP_{ij}} + b_2{Exposure_j}}_\\text{fixed} + \\underbrace{a_j + \\color{#DD3333}{b_{1j}NAP_{ij}} + \\epsilon_{ij}}_\\text{random}\n$$\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n$$\\epsilon_{ij} \\sim N(0, \\sigma^2_{\\epsilon})$$\n\n::: {.content-visible when-format=\"revealjs\"}\n. . .\n:::\n\n$$\\begin{bmatrix}\na_j \\\\\n\\color{#DD3333}{b_{1j}}\n\\end{bmatrix}\n\\sim N\\left(0,\n\\begin{matrix}\n\\sigma_a^2  & \\color{blue}{cov(a_j, b_{1j})} \\\\\n\\color{blue}{cov(a_j, b_{1j})} & \\color{#DD3333}{\\sigma_{b_{1j}}^2}\n\\end{matrix}\n\\right)\n$$\n\n::: {.notes}\nwe are thus adding 2 extra parameters:\n\n  *  random slope\n\n  * a covariance between the intercept and slope\n:::\n\n\n## Random regression\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](lec-06_intro_lmm_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=3600}\n:::\n:::\n\n\n\n\n$$\nRichness_{ij} = \\underbrace{a + b_1{NAP_{ij}} + b_2{Exposure_j}}_\\text{fixed} + \\underbrace{\\color{#DD3333}{a_j + b_{1j}NAP_{ij}} + \\epsilon_{ij}}_\\text{random}\n$$\n\n# Building a mixed model\n\n## Choosing effects\n\n### Fixed effects\n\n  a. based on question \n  b. based on confounding effects (think and justify based on causality)\n\n\\\n\n### Random effects\n  a. based on questions\n  b. based on data structure\n\n## Testing for effects\n\n### Fixed effects\n \nDegrees of freedom cannot be estimated exactly\n\nUse approximation (Satterwaite, Kenward-Rogers, ...)\n\n\\\n\n### Random effects\n\nLikelihood Ratio test\n\nFit model with and without a random effect using REML and then compare\n\n# Happy modelling {.unnumbered}\n\n![](assets/img_l5/unicorn.png){fig-align=\"center\"}\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}